name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
       python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
    - name: Test with pytest
      run: python -m pytest tests/
    - name: Stress Test with stress.py
      run: python stress.py
    - uses: actions/upload-artifact@v2
      with:
        name: test_chart.png
        path: outputs/chart.png
      
        
        
